project 'Cowa.xcodeproj'
platform :ios, '12.0'
use_frameworks!

target 'Cowa' do
    pod 'Alamofire', '~> 5.2'
    pod 'INTULocationManager', '~> 4.2.0'
    pod 'SnapKit', '~> 5.0.1'
    pod 'JVFloatingDrawer', '~> 0.1.0'
    pod 'DynamicButton', '~> 6.2.1'
    pod 'RETableViewManager'
    pod 'FXBlurView', '~> 1.6.4'
    pod 'FLEX'

    pod 'MGSwipeTableCell', '~> 1.5.5'

    pod 'ReachabilitySwift', '~> 5.0'
    pod 'Toast-Swift', '~> 5.0.1'
    pod 'DLRadioButton', '~> 1.4'

    pod 'SVProgressHUD'

    pod 'CCHMapClusterController'
    pod 'JZLocationConverter'

    pod 'SwiftyJSON', '~> 5.0'
    pod 'RESideMenu', '~> 4.0.7'

    pod 'SwiftLocation', '~> 5.0.2'
    pod 'BaiduWalkNaviKit', '~> 6.0.0'

end
